### ISSUE TITLE
FMS does not clear the state of the first recovery action.

### ISSUE THREAD

**Issue by ashish235** [openbaton/fm-system#7]
Hi Team, 

I 've a VNF, for which I 'm monitoring the health of the service inside the VNF. Now when an alarm is raised for the VNF, the healing script is invoked. Now after the service is healed if an alarm is generated again, FMS doesn't take any action. 

Please let me know what all specific logs/inputs you need. 

Regards,
Ashish

**Comment by marcellom** [comment]
I confirm this bug, I am working on it.

**Comment by marcellom** [comment]
@ashish235 I fixed this problem with https://github.com/openbaton/fm-system/pull/8, I will make a new release of the FMS containing this fix and provide a new Debian package (which will be included in the bootstrap).
